// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH9RAWS24Py7KV640PJSWOJaFVC7BDM8I',
    appId: '1:172698472102:web:35a9e567dc62bcb0e3ae67',
    messagingSenderId: '172698472102',
    projectId: 'notes-taking-ed92c',
    authDomain: 'notes-taking-ed92c.firebaseapp.com',
    storageBucket: 'notes-taking-ed92c.firebasestorage.app',
    measurementId: 'G-TP2GZQ6VK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSxQBme2uuWVZii459ppEMeaerX5p1x5Q',
    appId: '1:172698472102:android:12ca12768c6f001fe3ae67',
    messagingSenderId: '172698472102',
    projectId: 'notes-taking-ed92c',
    storageBucket: 'notes-taking-ed92c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANZprsZaG77sTwXOZQk9lyQwm6iOk8Nzs',
    appId: '1:172698472102:ios:594cfee2d8e8592be3ae67',
    messagingSenderId: '172698472102',
    projectId: 'notes-taking-ed92c',
    storageBucket: 'notes-taking-ed92c.firebasestorage.app',
    iosBundleId: 'com.example.notesTakingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANZprsZaG77sTwXOZQk9lyQwm6iOk8Nzs',
    appId: '1:172698472102:ios:594cfee2d8e8592be3ae67',
    messagingSenderId: '172698472102',
    projectId: 'notes-taking-ed92c',
    storageBucket: 'notes-taking-ed92c.firebasestorage.app',
    iosBundleId: 'com.example.notesTakingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH9RAWS24Py7KV640PJSWOJaFVC7BDM8I',
    appId: '1:172698472102:web:5c11be0330d33f94e3ae67',
    messagingSenderId: '172698472102',
    projectId: 'notes-taking-ed92c',
    authDomain: 'notes-taking-ed92c.firebaseapp.com',
    storageBucket: 'notes-taking-ed92c.firebasestorage.app',
    measurementId: 'G-P6755BCM71',
  );
}
